[profile.default]
src = "contracts"
out = "foundry/out"
test = "foundry/test"
script = "foundry/script"
libs = ["foundry/lib"]
cache_path = "foundry/cache"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
